import type { Metadata } from 'next';
import { Inconsolata } from 'next/font/google';
import styles from './root.module.css';
import Link from 'next/link';

const inconsolata = Inconsolata({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-inconsolata',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inconsolata.className}>
        <header className={styles.header}>
          <h1 className={styles.homeLink}>
            <Link href={'/home'}>Globalmantics</Link>
          </h1>
          <h3 className={styles.menuBarLink}>
            <Link href={'/blog'}>Blog</Link>
          </h3>
          <h3 className={styles.menuBarLink}>
            <Link href={'/settings'}>Settings</Link>
          </h3>
          <h3 className={styles.menuBarLink}>
            <Link href={'/conference'}>Conference</Link>
          </h3>
        </header>
        {children}
      </body>
    </html>
  );
}
